import { Router } from "express";
import { healthRouter } from "./health.routes";
import { attendanceRouter } from "../modules/attendance/attendance.routes";
import { auditLogsRouter } from "../modules/audit-logs/audit-logs.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { fieldStockRouter } from "../modules/field-stock/field-stock.routes";
import { filesRouter } from "../modules/files/files.routes";
import { locationsRouter } from "../modules/locations/locations.routes";
import { notificationsRouter } from "../modules/notifications/notifications.routes";
import { ordersRouter } from "../modules/orders/orders.routes";
import { pharmaciesRouter } from "../modules/pharmacies/pharmacies.routes";
import { placementsRouter } from "../modules/placements/placements.routes";
import { productsRouter } from "../modules/products/products.routes";
import { schedulesRouter } from "../modules/schedules/schedules.routes";
import { settingsRouter } from "../modules/settings/settings.routes";
import { targetsRouter } from "../modules/targets/targets.routes";
import { teamsRouter } from "../modules/teams/teams.routes";
import { usersRouter } from "../modules/users/users.routes";
import { visitPlansRouter } from "../modules/visit-plans/visit-plans.routes";
import { visitsRouter } from "../modules/visits/visits.routes";
import { warehouseRouter } from "../modules/warehouse/warehouse.routes";

export const apiRouter = Router();

apiRouter.use("/health", healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/teams", teamsRouter);
apiRouter.use("/pharmacies", pharmaciesRouter);
apiRouter.use("/placements", placementsRouter);
apiRouter.use("/products", productsRouter);
apiRouter.use("/targets", targetsRouter);
apiRouter.use("/schedules", schedulesRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/visits", visitsRouter);
apiRouter.use("/visit-plans", visitPlansRouter);
apiRouter.use("/locations", locationsRouter);
apiRouter.use("/warehouse", warehouseRouter);
apiRouter.use("/orders", ordersRouter);
apiRouter.use("/field-stock", fieldStockRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/audit-logs", auditLogsRouter);
apiRouter.use("/files", filesRouter);
apiRouter.use("/notifications", notificationsRouter);
